(define (problem BLOCKS-5-CLEAR)
(:domain BLOCKS)
(:objects a b c d e)
(:init
    (ontable a)
    (on b a)
    (on c b)
    (ontable d)
    (ontable e)
    (clear c)
    (clear d)
    (clear e)
    (handempty))
(:goal (and (clear a))))
